//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.accounts = new HashSet<account>();
            this.cashiers = new HashSet<cashier>();
            this.invoices = new HashSet<invoice>();
            this.itemsDecriptions = new HashSet<itemsDecription>();
            this.refunds = new HashSet<refund>();
            this.supplyOrders = new HashSet<supplyOrder>();
            this.transactionsHistories = new HashSet<transactionsHistory>();
            this.transactionsHistories1 = new HashSet<transactionsHistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<bool> isDefault { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual account account { get; set; }
        public virtual ICollection<cashier> cashiers { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual ICollection<itemsDecription> itemsDecriptions { get; set; }
        public virtual ICollection<refund> refunds { get; set; }
        public virtual ICollection<supplyOrder> supplyOrders { get; set; }
        public virtual ICollection<transactionsHistory> transactionsHistories { get; set; }
        public virtual ICollection<transactionsHistory> transactionsHistories1 { get; set; }
    }
}
