//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashier
    {
        public cashier()
        {
            this.cashier_items = new HashSet<cashier_items>();
        }
    
        public int id { get; set; }
        public int branchId { get; set; }
        public Nullable<int> openedBy { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> serial { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<double> total { get; set; }
        public string paymentType { get; set; }
        public Nullable<int> customerId { get; set; }
        public string notes { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
        public virtual branch branch { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<cashier_items> cashier_items { get; set; }
    }
}
