//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.cashiers = new HashSet<cashier>();
        }
    
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> isCash { get; set; }
        public Nullable<double> currentCredit { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<int> dueDay { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<cashier> cashiers { get; set; }
    }
}
