//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.accounts = new HashSet<account>();
            this.groupPermissions = new HashSet<groupPermission>();
        }
    
        public int id { get; set; }
        public string groupName { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual account account { get; set; }
        public virtual ICollection<groupPermission> groupPermissions { get; set; }
    }
}
