//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class inven_Settings
    {
        public int id { get; set; }
        public int branchId { get; set; }
        public Nullable<int> checkDays { get; set; }
        public Nullable<System.DateTime> lastCheckDate { get; set; }
    }
}
