//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class favStoreEntities : DbContext
    {
        public favStoreEntities()
            : base("name=favStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<cashier> cashiers { get; set; }
        public virtual DbSet<cashier_items> cashier_items { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<default_list> default_list { get; set; }
        public virtual DbSet<groupPermission> groupPermissions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<inven_Settings> inven_Settings { get; set; }
        public virtual DbSet<invoice_items> invoice_items { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<itemsDecription> itemsDecriptions { get; set; }
        public virtual DbSet<location_items> location_items { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<refund_iems> refund_iems { get; set; }
        public virtual DbSet<refund> refunds { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supplyOrder> supplyOrders { get; set; }
        public virtual DbSet<supplyOrders_items> supplyOrders_items { get; set; }
        public virtual DbSet<transactionsHistory> transactionsHistories { get; set; }
        public virtual DbSet<transactionType> transactionTypes { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
    }
}
