//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invoice_items = new HashSet<invoice_items>();
        }
    
        public int id { get; set; }
        public int branchId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
        public string refNo { get; set; }
        public Nullable<int> serialNo { get; set; }
        public Nullable<double> discountCash { get; set; }
        public Nullable<double> discountCommercial { get; set; }
        public Nullable<double> extraExpenses { get; set; }
        public Nullable<double> totalInvoice { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> openedBy { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> taxValue { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<invoice_items> invoice_items { get; set; }
    }
}
