//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_items
    {
        public int id { get; set; }
        public int invoiceId { get; set; }
        public int branchId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> total { get; set; }
        public string notes { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> taxValue { get; set; }
        public Nullable<double> totalWithTax { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual itemsDecription itemsDecription { get; set; }
    }
}
