//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsDecription
    {
        public itemsDecription()
        {
            this.cashier_items = new HashSet<cashier_items>();
            this.invoice_items = new HashSet<invoice_items>();
            this.refund_iems = new HashSet<refund_iems>();
            this.supplyOrders_items = new HashSet<supplyOrders_items>();
            this.transactionsHistories = new HashSet<transactionsHistory>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int id { get; set; }
        public string subject { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> supplierId { get; set; }
        public string code { get; set; }
        public Nullable<int> branchId { get; set; }
        public Nullable<int> lastEditBy { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
    
        public virtual account account { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<cashier_items> cashier_items { get; set; }
        public virtual ICollection<invoice_items> invoice_items { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual ICollection<refund_iems> refund_iems { get; set; }
        public virtual ICollection<supplyOrders_items> supplyOrders_items { get; set; }
        public virtual ICollection<transactionsHistory> transactionsHistories { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
