//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_items
    {
        public location_items()
        {
            this.transactionsHistories = new HashSet<transactionsHistory>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> palltaId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> palltaType { get; set; }
    
        public virtual ICollection<transactionsHistory> transactionsHistories { get; set; }
        public virtual location location { get; set; }
        public virtual transactionType transactionType { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
