//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class refund
    {
        public refund()
        {
            this.refund_iems = new HashSet<refund_iems>();
        }
    
        public int id { get; set; }
        public int branchId { get; set; }
        public Nullable<int> cashierId { get; set; }
        public Nullable<int> openedBy { get; set; }
        public Nullable<int> serial { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual account account { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<refund_iems> refund_iems { get; set; }
    }
}
