//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionsHistory
    {
        public int id { get; set; }
        public int transactionId { get; set; }
        public int currentBranchId { get; set; }
        public int locationItemId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<int> transactionTypeId { get; set; }
        public Nullable<int> fromBranchId { get; set; }
        public Nullable<int> toBranchId { get; set; }
        public string reason { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> serialNo { get; set; }
        public int itemId { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual branch branch1 { get; set; }
        public virtual location_items location_items { get; set; }
        public virtual transactionType transactionType { get; set; }
        public virtual itemsDecription itemsDecription { get; set; }
    }
}
